# delelopment
system:
  # 设定模式(debug/release/test,正式版改为release)
  mode: debug
  # url前缀
  url-path-prefix: sky
  # 程序监听端口
  port: 8088
  # 是否初始化数据(没有初始数据时使用, 已发布正式版改为false)
  init-data: true
  # rsa公钥文件路径(config.yml相对路径, 也可以填绝对路径)
  rsa-public-key: sky-pub.pem
  # rsa私钥文件路径(config.yml相对路径, 也可以填绝对路径)
  rsa-private-key: sky-priv.pem
  #数据库类型
  database-type: mysql
logs:
  # 日志等级(-1:Debug, 0:Info, 1:Warn, 2:Error, 3:DPanic, 4:Panic, 5:Fatal, -1<=level<=5, 参照zap.level源码)
  level: -1
  # 日志路径
  path: logs
  # 文件最大大小, M
  max-size: 50
  # 备份数
  max-backups: 100
  # 存放时间, 天
  max-age: 30
  # 是否压缩
  compress: false
#sqlite sqlite.open("{file-path}")
#mysql mysql.open("{username}:{password}@tcp({host}:{port})/{database}?charset={charset}&collation={collation}&{query}")
database:
  #sqlite 文件路径
  file-path: sky.db
  # 用户名
  username: root
  # 密码
  password: 123456
  # 数据库名
  database: sky
  # 主机地址
  host: localhost
  # 端口
  port: 3306
  # 连接字符串参数
  query: parseTime=True&loc=Local&timeout=10000ms
  # 是否打印日志
  log-mode: True
  # 编码方式
  charset: utf8mb4
  # 字符集(utf8mb4_general_ci速度比utf8mb4_unicode_ci快些)
  collation: utf8mb4_general_ci
  # 表名前缀
  table-prefix: sky_
  #启用连接池
  enable-pool: false
  # 最大空闲连接数
  max-idle: 5
  # 最大可打开连接数
  max-open: 10
  # 连接可复用的最大时间(单位秒)
  conn-max-lifetime: 3600
# casbin配置
casbin:
  # 模型配置文件, config.yml相对路径
  model-path: 'rbac_model.conf'

# jwt配置
jwt:
  # jwt标识
  realm: sky jwt
  # 服务端密钥
  key: secret key
  # token过期时间, 小时
  timeout: 12
  # 刷新token最大过期时间, 小时
  max-refresh: 12

# 令牌桶限流配置
rate-limit:
  # 填充一个令牌需要的时间间隔,毫秒
  fill-interval: 50
  # 桶容量
  capacity: 200